// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjymoaTQzNSxmSBKc5yVdfZto5DxOdbg8',
    appId: '1:280616341211:web:2a72cc1695b866e98a46fe',
    messagingSenderId: '280616341211',
    projectId: 'pet-aggregator-app',
    authDomain: 'pet-aggregator-app.firebaseapp.com',
    storageBucket: 'pet-aggregator-app.firebasestorage.app',
    measurementId: 'G-2MJ12542QT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8d66Zvu9SJyxClcu6azn9gzz1_saYwHQ',
    appId: '1:280616341211:android:622cf4f2956d2c258a46fe',
    messagingSenderId: '280616341211',
    projectId: 'pet-aggregator-app',
    storageBucket: 'pet-aggregator-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIToEX4YsvTV6tS79Wu0-EErdG0mx3vSg',
    appId: '1:280616341211:ios:c0d5b3690fb0d7e08a46fe',
    messagingSenderId: '280616341211',
    projectId: 'pet-aggregator-app',
    storageBucket: 'pet-aggregator-app.firebasestorage.app',
    iosBundleId: 'com.example.petAggregatorApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIToEX4YsvTV6tS79Wu0-EErdG0mx3vSg',
    appId: '1:280616341211:ios:c0d5b3690fb0d7e08a46fe',
    messagingSenderId: '280616341211',
    projectId: 'pet-aggregator-app',
    storageBucket: 'pet-aggregator-app.firebasestorage.app',
    iosBundleId: 'com.example.petAggregatorApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjymoaTQzNSxmSBKc5yVdfZto5DxOdbg8',
    appId: '1:280616341211:web:3128ec03aa70bb9e8a46fe',
    messagingSenderId: '280616341211',
    projectId: 'pet-aggregator-app',
    authDomain: 'pet-aggregator-app.firebaseapp.com',
    storageBucket: 'pet-aggregator-app.firebasestorage.app',
    measurementId: 'G-YP0QH6ERDK',
  );
}
